name: Build 3DS CIA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup devkitPro
        run: |
          sudo apt update
          sudo apt install -y curl git

          curl -L https://apt.devkitpro.org/install-devkitpro-pacman | sudo bash

          sudo dkp-pacman -Syu --noconfirm
          sudo dkp-pacman -S --noconfirm devkitARM libctru 3ds-dev

      - name: Set environment variables
        run: |
          echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
          echo "/opt/devkitpro/tools/bin" >> $GITHUB_PATH

      - name: Build project
        run: |
          make

      - name: Create CIA
        run: |
          mkdir -p output
          makerom -f cia \
            -o output/app.cia \
            -rsf rom.rsf \
            -target t \
            -exefslogo \
            -elf hackbuilder.elf

      - name: Upload CIA
        uses: actions/upload-artifact@v4
        with:
          name: CIA
          path: output/app.cia
